"""Building candidate pools: the lattice every record graph lives in.

Measured on the published graphs (see docs/CONSTRUCTIONS.md section 5 and the
numbers below), every record is

    G = L  union  theta_4(S),      theta_4 = rotation by arccos(7/8)

with L and S both subsets of the additive lattice generated by the 30 unit
vectors

    w(k, j) = exp(i * (k*60deg + j*theta_3/2)),   k = 0..5,  j = -2..2

where theta_3/2 = arcsin(1/sqrt12), so cos = sqrt33/6 and sin = sqrt3/6.
L and S share only the origin.  Both lie in Q(sqrt3, sqrt11); the rotation
theta_4 is what brings in sqrt5 (sin theta_4 = sqrt15/8), which is why the
two parts of a record graph can be told apart by whether sqrt5 appears in
the coordinates.

Measured on 510 (Parts) and 553 (Heule):

    part      vertices  unit vectors used   BFS depth   max radius
    L (510)      375         30 (|j|<=2)       4          2.024
    S (510)      135         18 (|j|<=1)       3          2.432
    L (553)      420         42 (|j|<=3)       3          2.000
    S (553)      133         18               3          2.524

So the pools built here are "all sums of at most d lattice vectors within a
radius", exactly Heule's Minkowski-sum construction (V_31 (+) V_151 (+) ...),
optionally clipped after every step.  Edges are found by a floating-point
prefilter followed by the EXACT test in K, so no edge is ever wrong; the
float pass only decides which pairs are worth testing exactly, and with a
tolerance of 1e-9 on numbers of size ~10 it cannot miss one.
"""
from __future__ import annotations
import math
from .field import K, Pt, is_unit

# ---- floats, only ever used for filtering and clipping ------------------
# This table is the square root of each basis element, so it depends on the
# field (hn.field.set_primes).  Getting it wrong is not a small error: the
# edge finder uses it to prefilter pairs, so a stale table silently DROPS real
# unit edges and the graph then looks 4-colourable.  refresh_field() rebuilds
# it; set_primes callers must invoke that.
_SQ = ()


def _basis_products():
    from .field import PRIMES
    out = []
    for i in range(8):
        m = 1
        for k in range(3):
            if i >> k & 1:
                m *= PRIMES[k]
        out.append(math.sqrt(m))
    return tuple(out)


def to_float(k: K) -> float:
    return sum(a * s for a, s in zip(k.n, _SQ)) / k.d


def pt_float(p: Pt):
    return (to_float(p.x), to_float(p.y))


def norm(p: Pt) -> float:
    return math.sqrt(to_float(p.norm2()))


# ---- exact rotations ------------------------------------------------------
ORIGIN = Pt(K.zero(), K.zero())

# (cos, sin) pairs, all exact in K.  Built through a function because the
# field is a parameter (hn.field.set_primes): in Q(sqrt3, sqrt5, sqrt7), for
# instance, sqrt11 does not exist and theta_3 simply has no entry.  Call
# rebuild_rot() after changing the field.
_ROT_SPEC = (
    ("theta1",   (1, 2), 3, 1, 2),        # 60 degrees
    ("theta3",   (5, 6), 11, 1, 6),       # arccos(5/6)
    ("theta3/2", None, None, None, None),  # arcsin(1/sqrt12), built specially
    ("theta4",   (7, 8), 15, 1, 8),       # arccos(7/8)
)


def rebuild_rot():
    t = {}
    for name, cos, m, num, den in _ROT_SPEC:
        try:
            if name == "theta3/2":
                t[name] = (K.root(33) * K.rat(1, 6), K.root(3) * K.rat(1, 6))
            else:
                t[name] = (K.rat(*cos), K.root(m) * K.rat(num, den))
        except AssertionError:
            pass                    # this rotation does not live in this field
    ROT.clear()
    ROT.update(t)
    return ROT


ROT = {}


def refresh_field():
    """Re-derive everything in this module that depends on the field."""
    global _SQ
    _SQ = _basis_products()
    return rebuild_rot()


refresh_field()


def rotate(p: Pt, cs, inverse=False) -> Pt:
    c, s = cs
    if inverse:
        s = -s
    return Pt(p.x * c - p.y * s, p.x * s + p.y * c)


def theta4(p: Pt, inverse=False) -> Pt:
    return rotate(p, ROT["theta4"], inverse)


def uses_sqrt5(p: Pt) -> bool:
    """True if the second generator occurs in either coordinate.

    In the classical field that generator is sqrt5, and its presence is the
    signature of theta_4: it tells the two parts of a record graph apart.
    """
    return any(p.x.n[i] or p.y.n[i] for i in (2, 3, 6, 7))


# ---- the lattice vectors --------------------------------------------------
def unit_vector_family(jmax=2):
    """The 6*(2*jmax+1) unit vectors  exp(i*(k*60deg + j*theta_3/2)),  |j|<=jmax.

    jmax=2 gives the 30 vectors of every part of every record graph;
    jmax=1 gives the 18 the small parts actually use; jmax=3 the 42 of
    Heule's 553-vertex large part.
    """
    out = []
    for j in range(-jmax, jmax + 1):
        v = Pt(K.rat(1), K.zero())
        for _ in range(abs(j)):
            v = rotate(v, ROT["theta3/2"], inverse=j < 0)
        for k in range(6):
            out.append(v)
            v = rotate(v, ROT["theta1"])
    assert all(is_unit(ORIGIN, v) for v in out)
    return out


# ---- point sets -----------------------------------------------------------
def dedup(points):
    seen, out = set(), []
    for p in points:
        k = p.key()
        if k not in seen:
            seen.add(k)
            out.append(p)
    return out


def clip(points, radius, eps=1e-9):
    r2 = radius * radius + eps
    return [p for p in points if to_float(p.norm2()) <= r2]


def minkowski(A, B, radius=None):
    """A (+) B, exact, deduplicated, optionally clipped to |p| <= radius."""
    out, seen = [], set()
    r2 = None if radius is None else radius * radius + 1e-9
    for a in A:
        for b in B:
            p = a + b
            if r2 is not None and to_float(p.norm2()) > r2:
                continue
            k = p.key()
            if k not in seen:
                seen.add(k)
                out.append(p)
    return out


def ball(vectors, depth, radius, step_radius=None):
    """All sums of at most `depth` vectors, clipped to |p| <= radius.

    `step_radius` clips after every step (Heule's V_151 is depth 2 clipped to
    1); by default only the final radius is applied.
    """
    W = [ORIGIN] + list(vectors)
    S = [ORIGIN]
    for d in range(depth):
        r = radius if d == depth - 1 or step_radius is None else step_radius
        S = minkowski(S, W, r)
    return S


def galois_orbit(points, masks=range(8)):
    return dedup([p.conj(m) for m in masks for p in points])


# ---- edges, exactly -------------------------------------------------------
def edges(points, tol=1e-9):
    """All unit-distance pairs among `points`, each confirmed exactly in K.

    A numpy float prefilter on the squared distance selects candidates; the
    exact test decides.  Returns sorted (i, j) pairs with i < j.
    """
    import numpy as np
    n = len(points)
    if n < 2:
        return []
    X = np.array([pt_float(p) for p in points])
    out = []
    # blocked so that the temporary matrix stays small
    B = 2048
    for i0 in range(0, n, B):
        xi = X[i0:i0 + B]
        d2 = ((xi[:, None, :] - X[None, :, :]) ** 2).sum(-1)
        ii, jj = np.nonzero(np.abs(d2 - 1.0) < tol)
        for a, b in zip(ii.tolist(), jj.tolist()):
            i, j = a + i0, b
            if i < j and is_unit(points[i], points[j]):
                out.append((i, j))
    out.sort()
    return out


def edges_grid(points, tol=1e-9):
    """Same answer as `edges`, but O(n) in space instead of O(n^2).

    The blocked float pass in `edges` builds a 2048 x n distance matrix, which
    at n ~ 150000 is 2.5 GB per block -- exactly the scale the rich joining
    rotations need (theta_28 wants a depth-6 ball of 78229 points, so a union
    of about 156000).  A unit distance moves a point by exactly 1, so bucketing
    on a unit grid leaves only the 9 neighbouring cells to test, and the whole
    pass is linear.

    Every surviving pair is still confirmed EXACTLY in K, so this changes the
    cost and not the answer; `test_edges_grid_matches` pins that.
    """
    import math
    n = len(points)
    if n < 2:
        return []
    XY = [pt_float(p) for p in points]
    cell = {}
    for i, (x, y) in enumerate(XY):
        cell.setdefault((math.floor(x), math.floor(y)), []).append(i)
    out = []
    for (cx, cy), idxs in cell.items():
        near = []
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                near += cell.get((cx + dx, cy + dy), ())
        for i in idxs:
            xi, yi = XY[i]
            for j in near:
                if j <= i:
                    continue
                xj, yj = XY[j]
                d2 = (xi - xj) ** 2 + (yi - yj) ** 2
                if abs(d2 - 1.0) < tol and is_unit(points[i], points[j]):
                    out.append((i, j))
    out.sort()
    return out


def contains(pool, points):
    """Which of `points` are in `pool`?  Returns (found, missing) index lists."""
    keys = {p.key() for p in pool}
    found = [i for i, p in enumerate(points) if p.key() in keys]
    missing = [i for i in range(len(points)) if i not in set(found)]
    return found, missing


def split_parts(points):
    """Indices of the sqrt5-free part L and the rotated part theta_4(S)."""
    L = [i for i, p in enumerate(points) if not uses_sqrt5(p)]
    S = [i for i, p in enumerate(points) if uses_sqrt5(p)]
    return L, S


def record_pool(depth_L=4, radius_L=2.03, depth_S=3, radius_S=2.45,
                jmax_L=2, jmax_S=2, step_radius_L=None, step_radius_S=None):
    """The ambient pool  ball_L  union  theta_4(ball_S), deduplicated.

    Defaults are the smallest parameters that contain the 510-vertex record
    (measured: L needs depth 4 and radius 2.024, S needs depth 3 and 2.432).
    Returns (points, index of the origin, boundary): points[:boundary] is
    the L side and points[boundary:] the rotated S side minus the shared
    origin.
    """
    WL = unit_vector_family(jmax_L)
    WS = unit_vector_family(jmax_S)
    L = ball(WL, depth_L, radius_L, step_radius_L)
    S = ball(WS, depth_S, radius_S, step_radius_S)
    RS = [theta4(p) for p in S]
    keys = {p.key() for p in L}
    extra = [p for p in RS if p.key() not in keys]
    pts = L + extra
    origin = next(i for i, p in enumerate(pts) if p.key() == ORIGIN.key())
    return pts, origin, len(L)
