"""Lattices inside a cyclotomic field, and their unit vectors -- exactly.

The joining criterion needs one thing from a lattice: the complete list of its
unit vectors, with no ball anywhere.  In the multiquadratic field `hn.lattice`
gets that from the trace form.  The same argument works over any number field,
and this is the cyclotomic case.

For `z` in `Q(zeta_n)` the trace form is

    q(z) = Tr(z conj(z)) = sum over sigma of |sigma(z)|^2,

positive definite because every term is.  `Q(zeta_n)` is abelian, so complex
conjugation lies in its Galois group and commutes with every `sigma`; hence
`sigma(z conj(z)) = sigma(z) conj(sigma(z))`, and a `z` of modulus 1 has every
conjugate of modulus 1 as well.  So

    |z| = 1   ==>   q(z) = deg = phi(n),

and the unit vectors of any subgroup are the integer points of one ellipsoid --
finite, enumerable, no radius parameter.

On the power basis the form is a Toeplitz matrix: `q` is Q-linear, so

    q(sum c_i zeta^i) = sum_{i,j} c_i c_j Tr(zeta^(i-j)),

and `Tr(zeta_n^k)` is the Ramanujan sum `mu(n/g) phi(n) / phi(n/g)` with
`g = gcd(n, k)`.
"""
from __future__ import annotations
from fractions import Fraction
from math import gcd


def _euler_phi(n):
    r, p = n, 2
    out = n
    while p * p <= r:
        if r % p == 0:
            while r % p == 0:
                r //= p
            out -= out // p
        p += 1
    if r > 1:
        out -= out // r
    return out


def _mobius(n):
    if n == 1:
        return 1
    out, p = 1, 2
    while p * p <= n:
        if n % p == 0:
            n //= p
            if n % p == 0:
                return 0
            out = -out
        p += 1
    return -out if n > 1 else out


def trace_zeta(n, k):
    """Tr_{Q(zeta_n)/Q}(zeta_n^k), the Ramanujan sum c_n(k)."""
    g = gcd(n, k % n)
    m = n // g
    return _mobius(m) * _euler_phi(n) // _euler_phi(m)


def power_basis_gram(n, deg):
    """Gram matrix of q(z) = Tr(z conj(z)) on 1, zeta, ..., zeta^(deg-1)."""
    return [[trace_zeta(n, i - j) for j in range(deg)] for i in range(deg)]


class CycLattice:
    """The Z-module generated by cyclotomic numbers, with its unit vectors."""

    def __init__(self, gens):
        import hn.cyclo as CY
        from math import gcd as _g
        deg = CY.DEG
        den = 1
        for x in gens:
            den = den * x.d // _g(den, x.d)
        rows = [[x.n[i] * (den // x.d) for i in range(deg)] for x in gens]
        self.den, self.deg, self.n = den, deg, CY.N
        self.basis = _hnf_rows(rows)
        self.rank = len(self.basis)
        G0 = power_basis_gram(self.n, deg)
        B = self.basis
        # q on the lattice basis, scaled by den^2 to stay integral
        self.gram = [[sum(B[a][i] * B[b][j] * G0[i][j]
                          for i in range(deg) for j in range(deg))
                      for b in range(self.rank)] for a in range(self.rank)]

    def shell(self, N, B=1):
        """Every lattice element of modulus squared N/B, exactly.

        For rational N/B the same argument as for unit vectors applies: the
        field is abelian, so conjugation is central in its Galois group and
        sigma(z conj(z)) = sigma(z) conj(sigma(z)); since z conj(z) = N/B is
        rational it is fixed, so every conjugate has the same modulus and

            Tr(z conj(z)) = deg * N / B.

        Cleaner than the multiquadratic case, where |z|^2 is usually irrational
        and a chart with congruences is needed.
        """
        import hn.cyclo as CY
        from hn.lattice import _ellipsoid_points
        from fractions import Fraction
        target = Fraction(self.deg * N, B) * self.den * self.den
        if target.denominator != 1:
            return []
        G = [[Fraction(x) for x in row] for row in self.gram]
        want = Fraction(N, B)
        out = []
        for c in _ellipsoid_points(G, target):
            v = [0] * self.deg
            for k, row in zip(c, self.basis):
                if k:
                    for i in range(self.deg):
                        v[i] += k * row[i]
            z = CY.Cyc(tuple(v), self.den)
            n2 = z * z.conj()
            if n2 == CY.Cyc.rat(want.numerator, want.denominator):
                out.append((tuple(c), z))
        return out

    def unit_vectors(self):
        """Every lattice element of modulus 1, exactly."""
        import hn.cyclo as CY
        from hn.lattice import _ellipsoid_points
        from fractions import Fraction
        target = Fraction(self.deg) * self.den * self.den
        G = [[Fraction(x) for x in row] for row in self.gram]
        out = []
        for c in _ellipsoid_points(G, target):
            v = [0] * self.deg
            for k, row in zip(c, self.basis):
                if k:
                    for i in range(self.deg):
                        v[i] += k * row[i]
            z = CY.Cyc(tuple(v), self.den)
            if (z * z.conj()).is_one():
                out.append((tuple(c), z))
        return out


def _hnf_rows(rows):
    """A basis of the Z-row-span, by integer row reduction."""
    M = [r[:] for r in rows if any(r)]
    if not M:
        return []
    ncol = len(M[0])
    r = 0
    for c in range(ncol):
        while True:
            nz = [i for i in range(r, len(M)) if M[i][c]]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda i: abs(M[i][c]))
            p = nz[0]
            for i in nz[1:]:
                q = M[i][c] // M[p][c]
                M[i] = [x - q * y for x, y in zip(M[i], M[p])]
        nz = [i for i in range(r, len(M)) if M[i][c]]
        if not nz:
            continue
        M[r], M[nz[0]] = M[nz[0]], M[r]
        r += 1
    return [row for row in M[:r]]
