"""The additive group a point set generates, and its unit vectors -- exactly.

Every sweep in this project tests a candidate by building a *ball* and running
SAT on it.  The ball is a parameter, and three times now a wrong conclusion has
come from one being too small (routes 20, 44, 48).  This module removes the
parameter for the one question that does not need it: the candidate's ambient
additive group.

    L and rho(L) both sit inside  Lambda = <L, rho(L)>,  a finitely generated
    subgroup of (C, +).  Anything true of Lambda is true of every ball in it,
    at every depth and radius, forever.

The object that makes this computable is the TRACE FORM.  For z = x + iy with
x, y in K = Q(sqrt m1, sqrt m2, sqrt m3), write x = sum_i x_i sqrt(m_i) over
the 8 squarefree divisors.  Summing |sigma(z)|^2 over the 8 Galois
automorphisms gives

    Tr(x^2 + y^2) = 8 * sum_i m_i (x_i^2 + y_i^2)

and every conjugate of a unit vector is again a unit vector, so

    |z| = 1   ==>   sum_i m_i (x_i^2 + y_i^2) = 1.

The left side is a POSITIVE DEFINITE rational quadratic form in the
coordinates.  So the unit vectors of any subgroup of K^2 are the integer
points of an ellipsoid -- a finite, enumerable set, with no radius parameter
anywhere.  For the Moser lattice in the chart

    z = (a + b sqrt33)/12 + i (c sqrt3 + d sqrt11)/12

the form is exactly  a^2 + 33 b^2 + 3 c^2 + 11 d^2 = 144,  which is where that
equation comes from; it has 30 solutions obeying the rationality side
condition ab + cd = 0, and they are the 30 unit vectors.

Enumeration is Fincke-Pohst over an exact rational LDL^T factorisation -- no
floating point, so the bound cannot be off by one and silently drop a unit
vector.  Dropping one would be fatal: `hn.algcolour` would then certify a
4-colouring that is not proper.
"""
from __future__ import annotations
from fractions import Fraction
from .field import K, Pt, PRIMES


# ---- coordinates as rational vectors --------------------------------------
def coeff_vector(p: Pt):
    """The 16 rational coordinates of a point: 8 for x, then 8 for y."""
    return tuple([Fraction(a, p.x.d) for a in p.x.n]
                 + [Fraction(a, p.y.d) for a in p.y.n])


def from_coeff_vector(v):
    """Inverse of coeff_vector."""
    def build(cs):
        den = 1
        for c in cs:
            den = den * c.denominator // _gcd(den, c.denominator)
        return K(tuple(int(c * den) for c in cs), den)
    return Pt(build(v[:8]), build(v[8:]))


def _gcd(a, b):
    while b:
        a, b = b, a % b
    return abs(a)


# ---- the group generated by a point set -----------------------------------
def _xgcd(a, b):
    """(g, x, y) with x*a + y*b == g == gcd(a, b)."""
    x0, x1, y0, y1 = 1, 0, 0, 1
    while b:
        q = a // b
        a, b = b, a - q * b
        x0, x1 = x1, x0 - q * x1
        y0, y1 = y1, y0 - q * y1
    if a < 0:
        a, x0, y0 = -a, -x0, -y0
    return a, x0, y0


def _hnf(rows):
    """Row echelon basis over Z of the subgroup the rows generate.

    Each elimination step replaces a pair of rows by a UNIMODULAR combination
    built from the extended gcd, so the span is preserved exactly and the
    entries stay bounded.  The obvious alternative -- repeated floor-division
    reduction with swaps -- is also correct but suffers coefficient explosion:
    over Q(sqrt3, sqrt11, sqrt247), where the coordinates scale by 1536, it
    does not terminate in any usable time.
    """
    rows = [list(r) for r in rows if any(r)]
    if not rows:
        return []
    n = len(rows[0])
    r = 0
    for col in range(n):
        piv = next((i for i in range(r, len(rows)) if rows[i][col]), None)
        if piv is None:
            continue
        rows[r], rows[piv] = rows[piv], rows[r]
        for i in range(r + 1, len(rows)):
            if rows[i][col]:
                a, b = rows[r][col], rows[i][col]
                g, x, y = _xgcd(a, b)
                u = [x * p + y * q for p, q in zip(rows[r], rows[i])]
                v = [(-b // g) * p + (a // g) * q
                     for p, q in zip(rows[r], rows[i])]
                rows[r], rows[i] = u, v
        if rows[r][col] < 0:
            rows[r] = [-a for a in rows[r]]
        r += 1
        if r == len(rows):
            break
    return [row for row in rows[:r] if any(row)]


class Lattice:
    """The additive group generated by a list of points, with a Z-basis.

    `basis` is a list of Pt; `rank` its length.  `scale` is the common
    denominator used internally, so that every generator has integer
    coordinates after multiplying by it.
    """

    def __init__(self, points):
        vecs = [coeff_vector(p) for p in points]
        den = 1
        for v in vecs:
            for c in v:
                den = den * c.denominator // _gcd(den, c.denominator)
        rows = [[int(c * den) for c in v] for v in vecs]
        ech = _hnf(rows)
        red = _lll(ech, _weights())
        self.scale = den
        self.echelon = ech                       # for containment tests
        self.int_basis = red                     # integer rows, /scale = real
        self.rank = len(red)
        self.basis = [from_coeff_vector(tuple(Fraction(a, den) for a in row))
                      for row in red]
        self.primes = tuple(PRIMES)
        self.divisors = tuple(basis_radicands())

    # ---- the trace form -------------------------------------------------
    def gram(self):
        """Integer Gram matrix G with  n^T G n = scale^2 * sum_i m_i(x_i^2+y_i^2).

        Positive definite, so {n : n^T G n = scale^2} is a finite ellipsoid and
        contains every unit vector of the group.
        """
        w = _weights()                           # weights for x then y
        B = self.int_basis
        r = self.rank
        return [[sum(w[k] * B[i][k] * B[j][k] for k in range(16))
                 for j in range(r)] for i in range(r)]

    def combine(self, n):
        """The point sum_k n_k * basis[k]."""
        den = self.scale
        acc = [0] * 16
        for c, row in zip(n, self.int_basis):
            if c:
                for k in range(16):
                    acc[k] += c * row[k]
        return Pt(K(tuple(acc[:8]), den), K(tuple(acc[8:]), den))

    def combine_echelon(self, n):
        """The point sum_k n_k * echelon[k] -- the inverse of `coords`.

        `combine` sums over the LLL basis while `coords` reads off the echelon
        one, so they are NOT inverse: `combine(coords(p))` is some other lattice
        point.  Anything that needs a representative for a given coordinate
        vector -- coset representatives modulo m*Lambda, for one -- has to use
        this, and `coords(combine_echelon(n)) == n` is asserted in the tests.
        """
        den = self.scale
        acc = [0] * 16
        for c, row in zip(n, self.echelon):
            if c:
                for k in range(16):
                    acc[k] += c * row[k]
        return Pt(K(tuple(acc[:8]), den), K(tuple(acc[8:]), den))

    def contains(self, p: Pt):
        """Is p in the group?  Solves the integer system by reduction."""
        return self.coords(p) is not None

    def coords(self, p: Pt):
        """p as an integer vector over `echelon`, or None if p is not in the group.

        The echelon basis, not the LLL one, is the coordinate system every
        caller sees: it is triangular, so the solve is exact and immediate, and
        `hn.algcolour` only ever needs *some* fixed basis.
        """
        v = coeff_vector(p)
        if any((c * self.scale).denominator != 1 for c in v):
            return None
        t = [int(c * self.scale) for c in v]
        n = []
        for row in self.echelon:
            col = next(i for i, a in enumerate(row) if a)
            if t[col] % row[col]:
                return None
            q = t[col] // row[col]
            n.append(q)
            if q:
                t = [a - q * b for a, b in zip(t, row)]
        return tuple(n) if not any(t) else None

    # ---- the finite, complete set of unit vectors ------------------------
    def unit_vectors(self):
        """Every element of the group at distance exactly 1 from the origin.

        Complete by construction: the trace form bounds the search to an
        ellipsoid, every integer point of which is tested EXACTLY in K.
        """
        G = self.gram()
        target = self.scale * self.scale
        out = []
        for n in _ellipsoid_points(G, target):
            p = self.combine(n)
            if p.norm2().is_one():
                out.append((self.coords(p), p))
        return out


def basis_radicands():
    """m[i] for K's basis element i, in K's own BITMASK order.

    NOT `squarefree_divisors()`, which sorts.  With PRIMES = (3, 5, 11) the two
    agree except at indices 3 and 4, where sorting swaps sqrt15 and sqrt11 --
    and a permuted weight vector makes the trace form the wrong ellipsoid, which
    found 10 of the Moser lattice's 30 unit vectors instead of all 30.  Silently
    dropping unit vectors is the one error this module must never make, so the
    order is derived here from the same rule K.__mul__ uses.
    """
    from .field import PRIMES as P
    out = []
    for i in range(8):
        m = 1
        for k in range(3):
            if i >> k & 1:
                m *= P[k]
        out.append(m)
    return out


def _weights():
    """The trace-form weight of each of the 16 rational coordinates."""
    m = basis_radicands()
    return list(m) + list(m)


def _lll(rows, w, delta=Fraction(3, 4)):
    """LLL-reduce integer rows under the weighted inner product sum_k w_k u_k v_k.

    Without this the enumeration is hopeless: the HNF basis of the Moser
    lattice has a Gram-Schmidt coefficient of 660/4054229, so Fincke-Pohst
    would sweep a window of about 940 values on the last variable instead of 3.

    Cohen's Algorithm 2.6.3 with the Gram-Schmidt data carried INCREMENTALLY.
    Recomputing it inside the reduction loop instead -- the obvious way to
    write this -- is correct but quartic, and over Q(sqrt3, sqrt11, sqrt247),
    where the trace-form weights run to 8151 and the scale to 1536, it does not
    finish.  Exact rational arithmetic throughout: an LLL that rounds could
    return a basis that is merely *probably* a basis, and every downstream
    claim rests on this one being right.
    """
    b = [list(r) for r in rows]
    n = len(b)
    if n <= 1:
        return b
    mu = [[Fraction(0)] * n for _ in range(n)]
    B = [Fraction(0)] * n
    star = [None] * n

    def recompute(i):
        v = [Fraction(x) for x in b[i]]
        for j in range(i):
            if B[j]:
                mu[i][j] = _fip(w, b[i], star[j]) / B[j]
                v = [a - mu[i][j] * sc for a, sc in zip(v, star[j])]
        star[i] = v
        B[i] = _fip(w, v, v)

    for i in range(n):
        recompute(i)

    k = 1
    while k < n:
        # size-reduce b[k] against b[k-1] .. b[0], updating mu as we go
        for j in range(k - 1, -1, -1):
            q = _nint(mu[k][j])
            if q:
                b[k] = [a - q * c for a, c in zip(b[k], b[j])]
                mu[k][j] -= q
                for i in range(j):
                    mu[k][i] -= q * mu[j][i]
        if B[k] >= (delta - mu[k][k - 1] ** 2) * B[k - 1]:
            k += 1
        else:
            b[k], b[k - 1] = b[k - 1], b[k]
            for i in range(k - 1, n):
                recompute(i)
            k = max(k - 1, 1)
    return b


def _fip(w, u, v):
    """Weighted inner product where either side may be rational."""
    return sum(Fraction(wk) * Fraction(a) * Fraction(c)
               for wk, a, c in zip(w, u, v))


def _nint(x: Fraction):
    """Nearest integer, ties away from zero."""
    return _floor(x + Fraction(1, 2)) if x >= 0 else -_floor(-x + Fraction(1, 2))


# ---- exact Fincke-Pohst ----------------------------------------------------
def _ldl(G):
    """Exact rational LDL^T:  Q(n) = sum_i d_i (n_i + sum_{j>i} u_ij n_j)^2."""
    r = len(G)
    A = [[Fraction(G[i][j]) for j in range(r)] for i in range(r)]
    d, U = [], [[Fraction(0)] * r for _ in range(r)]
    for i in range(r):
        d.append(A[i][i])
        assert d[i] > 0, "trace form is not positive definite"
        for j in range(i + 1, r):
            U[i][j] = A[i][j] / d[i]
        for j in range(i + 1, r):
            for k in range(j, r):
                A[j][k] -= d[i] * U[i][j] * U[i][k]
                A[k][j] = A[j][k]
    return d, U


def _ellipsoid_points(G, target):
    """All integer n != 0 with n^T G n == target.  Exact, complete.

    Standard Fincke-Pohst recursion on the LDL^T form, with rational bounds;
    only the final floor uses integer square root, so no float ever decides
    membership.
    """
    r = len(G)
    d, U = _ldl(G)
    n = [0] * r
    out = []

    def rec(i, rem):
        # rem = target - sum over already-fixed levels
        if i < 0:
            if rem == 0 and any(n):
                out.append(tuple(n))
            return
        c = sum(U[i][j] * n[j] for j in range(i + 1, r))
        # d_i (n_i + c)^2 <= rem  ->  |n_i + c| <= sqrt(rem/d_i)
        if rem < 0:
            return
        b = rem / d[i]
        # integer window for n_i
        lo_f = -c - _sqrt_up(b)
        hi_f = -c + _sqrt_up(b)
        lo = _ceil(lo_f)
        hi = _floor(hi_f)
        for v in range(lo, hi + 1):
            t = Fraction(v) + c
            nxt = rem - d[i] * t * t
            if nxt < 0:
                continue
            n[i] = v
            rec(i - 1, nxt)
            n[i] = 0

    rec(r - 1, Fraction(target))
    return out


def _sqrt_up(q: Fraction):
    """A rational >= sqrt(q), tight enough to keep the window small."""
    from math import isqrt
    if q <= 0:
        return Fraction(0)
    # sqrt(p/s) = sqrt(p*s)/s, and isqrt(x)+1 > sqrt(x)
    p, s = q.numerator, q.denominator
    return Fraction(isqrt(p * s) + 1, s)


def _floor(x: Fraction):
    return x.numerator // x.denominator


def _ceil(x: Fraction):
    return -((-x.numerator) // x.denominator)
