#!/usr/bin/env python3
"""Filter 1: kill a join candidate by arithmetic, with no ball and no SAT.

Usage:
    alg_filter.py --validate                 run the known cases (do this first)
    alg_filter.py --spindle 4 --primes 3,5,11
    alg_filter.py --shell 4/1 --jmax 2
    alg_filter.py --sweep-shells 5.0         every rational shell the lattice has

The test is: does the additive group generated by the lattice and its rotated
image admit a homomorphism onto a group of order 4 that kills no unit vector?
If it does, that homomorphism IS a proper 4-colouring of the whole infinite
group, so no subset of it is 5-chromatic at any radius or depth, and the
candidate is dead forever.  If it does not, NOTHING follows -- the lattice may
still be 4-colourable by a colouring that is not a homomorphism.

So this prints DEAD or unknown.  It never prints "5-chromatic", and a caller
who reads "unknown" as "promising" is making exactly the inference this filter
cannot support.
"""
import os, sys, time, argparse
from fractions import Fraction
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.joins import Join, spindle, rational_spindle, GROUND_TRUTH

ap = argparse.ArgumentParser()
ap.add_argument("--validate", action="store_true")
ap.add_argument("--spindle", type=int)
ap.add_argument("--shell", help="rational squared radius a/b")
ap.add_argument("--primes", help="e.g. 3,5,11")
ap.add_argument("--jmax", type=int, default=2)
ap.add_argument("--jmax-small", type=int)
ap.add_argument("--sweep-shells", type=float, metavar="RADIUS")
ap.add_argument("--depth", type=int, default=4)
ap.add_argument("--moduli", default="2,3,4",
                help="also try Cayley colourings of Lambda/m*Lambda")
ap.add_argument("--verify-ball", type=float, default=0.0,
                help="re-check a found colouring on a ball of this radius")
a = ap.parse_args()
log = lambda s: print(s, flush=True)


def run(j):
    """Returns (verdict, rank, n_units, n_certs, seconds) or None if unbuildable."""
    from hn.algcolour import certify
    built = j.build()
    if built is None:
        return None
    WL, WS, cs = built
    from hn.construct import rotate
    gen = list(WL) + [rotate(p, cs) for p in WS]
    t = time.time()
    mods = tuple(int(x) for x in a.moduli.split(",") if x.strip())
    v = certify(gen, moduli=mods)
    dt = time.time() - t
    kl = sum(1 for c in v.certs if c[0] == "klein")
    z4 = sum(1 for c in v.certs if c[0] == "z4")
    if v.periodic and not v.certs:
        log(f"             periodic certificate at m={v.periodic[1]} "
            f"({v.periodic[1] ** v.lattice.rank} cosets)")
    if v.dead and a.verify_ball:
        from hn.construct import ball, dedup, edges
        P = dedup(ball(WL, a.depth, a.verify_ball)
                  + [rotate(p, cs) for p in ball(WS, a.depth, a.verify_ball)])
        E = edges(P)
        from hn.algcolour import verify_verdict
        bad, col = verify_verdict(v, P, E)
        log(f"      ball check: {len(P)} pts {len(E)} edges, "
            f"{len(set(col.values()))} colours, {len(bad)} monochromatic edges"
            + ("   <-- CERTIFICATE IS WRONG" if bad else "   ok"))
    return v, kl, z4, dt


def line(j, res, expect=None, note=""):
    if res is None:
        log(f"{j.name:12s} {j.field_str():18s}  not a rotation in this field")
        return None
    v, kl, z4, dt = res
    verdict = "DEAD (4-colourable)" if v.dead else "unknown"
    flag = ""
    if expect:
        # A 5-chromatic case MUST come back unknown; a kill there is a bug.
        # A 4-colourable case MAY come back unknown -- that is merely no information.
        flag = "  <-- CONTRADICTS GROUND TRUTH" if (v.dead and expect == "5-chromatic") \
            else ("  ok" if not v.dead and expect == "5-chromatic"
                  else "  ok (kill)" if v.dead else "  no information")
    log(f"{j.name:12s} {j.field_str():18s} rank={v.lattice.rank} "
        f"units={len(v.units):4d} klein={kl:2d} z4={z4:2d}  {verdict:20s}"
        f"{dt*1000:8.0f} ms{flag}")
    if note:
        log(f"             {note}")
    return v


if a.validate:
    log("Filter 1 against the cases whose answers are already known.")
    log("A 5-chromatic case MUST come back 'unknown'; a kill there would be a bug.\n")
    for j, expect, why in GROUND_TRUTH:
        line(j, run(j), expect, f"truth: {expect} -- {why}")
    sys.exit(0)

if a.sweep_shells:
    from hn.field import set_primes
    import hn.construct as C
    import collections
    set_primes((3, 5, 11))
    C.refresh_field()
    from hn.construct import unit_vector_family, ball
    P = ball(unit_vector_family(a.jmax), a.depth, a.sweep_shells)
    shells = collections.Counter()
    for p in P:
        q = p.norm2()
        if not any(q.n[1:]):
            shells[Fraction(q.n[0], q.d)] += 1
    cand = [d2 for d2 in sorted(shells) if d2 > 0]
    log(f"ball depth {a.depth} radius {a.sweep_shells}: {len(P)} points, "
        f"{len(cand)} rational shells\n")
    dead = alive = 0
    for d2 in cand:
        j = rational_spindle(d2.numerator, d2.denominator,
                             jmax_L=a.jmax, jmax_S=a.jmax_small or a.jmax)
        v = line(j, run(j))
        if v is not None:
            dead += bool(v.dead)
            alive += not v.dead
    log(f"\n{dead} killed outright, {alive} survive and need a real test.")
    sys.exit(0)

primes = tuple(int(x) for x in a.primes.split(",")) if a.primes else None
if a.spindle:
    j = rational_spindle(a.spindle, 1, primes=primes, jmax_L=a.jmax,
                         jmax_S=a.jmax_small or a.jmax)
elif a.shell:
    n, _, d = a.shell.partition("/")
    j = rational_spindle(int(n), int(d or 1), primes=primes, jmax_L=a.jmax,
                         jmax_S=a.jmax_small or a.jmax)
else:
    ap.error("need --validate, --spindle, --shell or --sweep-shells")
line(j, run(j))
