#!/usr/bin/env python3
"""Classify EVERY joining rotation, without ever building a ball.

Usage: classify_joins.py [--amax 60] [--bmax 12] [--out FILE] [--time SECONDS]

Every 5-chromatic unit-distance graph in the literature has the shape

    G = L  union  theta(S),

two copies of the Moser lattice glued by one rotation.  Everybody uses
theta_4 = arccos(7/8).  Whether that is necessary or merely historical has
never been settled, because the only test anyone had was: build a ball, run
SAT, see if it is 5-chromatic.  That test has a free parameter -- the ball --
and this repository has three wrong verdicts on record from it being too small
(docs/ATTEMPTS.md routes 20, 44, 48).

This has no ball.  For a candidate rotation theta, the two halves both sit in

    Lambda_theta = < W  union  theta(W) >,

generated by the 30 unit vectors and their images -- a finitely generated
subgroup of (C, +), no radius anywhere.  hn.lattice enumerates its unit
vectors exactly as the integer points of the trace-form ellipsoid, and
hn.algcolour looks for a homomorphism phi : Lambda_theta -> G, |G| = 4, that
kills no unit vector.  If one exists, EVERY subset of Lambda_theta is
4-colourable, at every radius and depth, forever: theta is dead, permanently,
and the certificate is a pair of linear forms checkable by hand.

The kill is one-sided (see hn/algcolour.py), so a survivor is a CANDIDATE, not
a construction.  What the sweep produces is therefore an upper bound on the
set of joining rotations -- which is the thing nobody had.

Validated 8/8 against hn.joins.GROUND_TRUTH, including theta_9, which has
rank 8 and 126 unit vectors, exactly theta_4's profile, and dies anyway.  That
case is why this is not merely a rank test.
"""
import os, sys, time, argparse, json
from math import gcd
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.joins import rational_spindle, GROUND_TRUTH
from hn.algcolour import certify
from hn.construct import rotate

ap = argparse.ArgumentParser()
ap.add_argument("--amax", type=int, default=60)
ap.add_argument("--bmax", type=int, default=12)
ap.add_argument("--denoms", default=None,
                help="comma-separated denominators to sweep instead of 1..bmax. "
                     "Only denominators dividing 144 can occur at all: |z|^2 is "
                     "always an integer over 144 (results/SHELLS.md), so "
                     "1,2,3,4,6,8,9,12 are the only ones worth a sweep.")
ap.add_argument("--time", type=float, default=None)
ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..",
                                              "results", "JOIN-CLASSIFICATION.json"))
ap.add_argument("--skip-validate", action="store_true")
a = ap.parse_args()
log = lambda s: print(s, flush=True)


def verdict(J):
    """(dead, rank, nunits, seconds) with no ball built anywhere."""
    b = J.build()
    if b is None:
        return None
    WL, WS, cs = b
    gens = WL + [rotate(p, cs) for p in WS]
    t = time.time()
    v = certify(gens, limit=1)
    return v.dead, v.lattice.rank, len(v.units), time.time() - t


if not a.skip_validate:
    log("validating the filter against the eight rotations whose answers are known")
    bad = 0
    for J, truth, note in GROUND_TRUTH:
        r = verdict(J)
        if r is None:
            continue
        dead, rank, nu, dt = r
        agree = dead == (truth == "4-colourable")
        bad += not agree
        log(f"  {J.name:12} rank {rank} units {nu:4d} -> "
            f"{'dead' if dead else 'survives':9} vs {truth:14} "
            f"{'ok' if agree else '*** DISAGREES'}")
    if bad:
        log(f"FILTER IS UNSOUND on {bad} known cases; refusing to sweep")
        sys.exit(1)
    log("  8/8 -- sweeping\n")

DEN = ([int(x) for x in a.denoms.split(",")] if a.denoms
       else list(range(1, a.bmax + 1)))
seen, cands = set(), []
for b in DEN:
    for n in range(1, a.amax * b + 1):
        if gcd(n, b) != 1 or 4 * n <= b:
            continue
        J = rational_spindle(n, b)
        key = (J.cos, J.radicand, J.coeff, J.den)
        if key in seen:
            continue
        seen.add(key)
        cands.append(J)
log(f"{len(cands)} distinct rational spindles with squared radius a/b, "
    f"a/b <= {a.amax}, b <= {a.bmax}")

t0, rows, survivors, nofield = time.time(), [], [], 0
for i, J in enumerate(cands, 1):
    if a.time and time.time() - t0 > a.time:
        log(f"\ntime budget reached after {i-1} of {len(cands)}")
        break
    r = verdict(J)
    if r is None:
        nofield += 1
        continue
    dead, rank, nu, dt = r
    rows.append(dict(name=J.name, field=J.field_str(), cos=str(J.cos),
                     rank=rank, units=nu, dead=dead, seconds=round(dt, 2)))
    if not dead:
        survivors.append(J.name)
        log(f"  [{i:4d}/{len(cands)}] SURVIVES: {J.name:14} {J.field_str():18} "
            f"cos {str(J.cos):10} rank {rank} units {nu}")
    elif i % 25 == 0:
        log(f"  [{i:4d}/{len(cands)}] ... {len(survivors)} survivors so far "
            f"({time.time()-t0:.0f}s)")

log(f"\n{len(rows)} rotations decided, {nofield} do not exist in their field")
log(f"{len(rows)-len(survivors)} killed permanently by an explicit 4-colouring "
    f"of the whole infinite lattice")
log(f"{len(survivors)} survive: {survivors}")
os.makedirs(os.path.dirname(a.out), exist_ok=True)
with open(a.out, "w") as f:
    json.dump(dict(amax=a.amax, bmax=a.bmax, decided=len(rows),
                   survivors=survivors, rows=rows), f, indent=1)
log(f"written to {a.out}")
