#!/usr/bin/env python3
"""More than two sets of 42 vectors -- the extension de Grey asked for.

Usage: haugland_sets.py [--sets 3] [--depth 2] [--radius 2.2]

Aubrey de Grey, Polymath16 thread 18, 13 September 2026, on Haugland's
Moser-spindle-free graph (arXiv 2608.04542):

    "which I would love to explore as a possible way to beat the record of 509
     verties.  Plenty of avenues are apparent... most particularly, using more than
     just two sets of 42 vectors.  Anyone want to have a go?"

Haugland's lattice is generated by 84 unit vectors:

    u_{2j}   = (cos(pi j/21), sin(pi j/21))            42 rational-angle directions
    u_{2j+1} = (cos(pi(j+theta)/21), sin(pi(j+theta)/21))   the same, rotated by theta

with theta = (21/pi) phi - 14 and phi the angle of (-sqrt3, 4cos(pi/7) - 1).  That
vector has length exactly 4 sin(2 pi/7), so the perturbation

    rho = (-sqrt3 + i(4 cos(pi/7) - 1)) / (4 sin(2 pi/7)) * zeta_3^-1

is an exact element of Q(zeta_84) of modulus exactly 1, and reproduces the paper's
theta = 0.42363201413287 to fourteen places.  Two sets means {zeta_42^j, rho
zeta_42^j}; de Grey's suggestion is rho^k for k = 0, 1, 2, ...

**Why this needs conductor 420, and why route 38 missed it.**  Haugland's joining
rotation is theta_4 = (7 + i sqrt15)/8 -- the record's own rotation -- and sqrt15
needs sqrt5, which is not in Q(zeta_84) because 5 does not divide 84.  Route 38
swept zeta_42 and zeta_84 against the rotations *those* fields admit, so it tested
the heptagonal lattice without the rotation that works, and closed it.  420 = 4*3*5*7
is the smallest conductor holding the lattice and theta_4 at once.
"""
import os, sys, time, argparse, collections
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import hn.cyclo as C
from hn.cyclo import Cyc, ball, dedup, edges
from hn.sat import find_triangle
from hn.minimise import verify
from hn.graph import induced
from hn.io import save_points, save_edges

ap = argparse.ArgumentParser()
ap.add_argument("--sets", type=int, default=3)
ap.add_argument("--depth", type=int, default=2)
ap.add_argument("--radius", type=float, default=2.2)
ap.add_argument("--degree", type=int, default=4)
ap.add_argument("--sizes-only", action="store_true")
ap.add_argument("--cube", type=int, default=0,
                help="split on this many vertices and use cube and conquer instead of "
                     "one CDCL call; direct solving stops deciding these instances "
                     "well below the size the classical lattice handles")
ap.add_argument("--procs", type=int, default=8)
a = ap.parse_args()
log = lambda s: print(f"[{time.strftime('%H:%M:%S')}] {s}", flush=True)

N = 420
C.set_conductor(N)
z = lambda k: Cyc.zeta(k % N)
half = Cyc.rat(1, 2)
r3 = z(35) + z(-35)                                   # zeta_12 + inverse = sqrt3
cpi7 = (z(30) + z(-30)) * half                        # cos(pi/7)
s2p7 = (z(60) - z(-60)) * (half * z(-105))            # (zeta_7 - inv)/(2i)
vec = (Cyc.zero() - r3) + z(105) * (cpi7 * Cyc.rat(4) - Cyc.rat(1))
rho = vec * (s2p7 * Cyc.rat(4)).inv() * z(-140)       # divide by 4sin, then by zeta_3
g5 = Cyc.zero()
for k in (1, 4):
    g5 = g5 + z(84 * k)
for k in (2, 3):
    g5 = g5 - z(84 * k)                               # Gauss sum: g5^2 = 5
r15 = r3 * g5
t4 = Cyc.rat(7, 8) + z(105) * r15 * Cyc.rat(1, 8)     # theta_4 = (7 + i sqrt15)/8
log(f"Q(zeta_{N}): degree {C.DEG}; rho modulus 1 {(rho*rho.conj()).is_one()}; "
    f"sqrt15^2 == 15 {(r15*r15) == Cyc.rat(15)}; theta_4 modulus 1 "
    f"{(t4*t4.conj()).is_one()}")

W, seen = [], set()
p = Cyc.rat(1)
for k in range(a.sets):
    for j in range(42):
        w = p * z(10 * j)
        if w.key() not in seen:
            seen.add(w.key())
            W.append(w)
    p = p * rho
log(f"{a.sets} sets of 42 -> {len(W)} distinct unit directions")

t = time.time()
L = ball(W, a.depth, a.radius)
log(f"ball depth {a.depth} radius {a.radius}: {len(L)} points  ({time.time()-t:.0f}s)")
if a.sizes_only:
    sys.exit(0)
t = time.time()
R = [t4 * q for q in L]
U = dedup(L + R)
E = edges(U)
log(f"union with theta_4: {len(U)} points, {len(E)} edges  ({time.time()-t:.0f}s)")


def kcore(n, Ed, d):
    adj = collections.defaultdict(set)
    for u, v in Ed:
        adj[u].add(v)
        adj[v].add(u)
    alive = set(range(n))
    q = [v for v in alive if len(adj[v]) < d]
    while q:
        v = q.pop()
        if v not in alive:
            continue
        alive.discard(v)
        for w in adj[v]:
            if w in alive:
                adj[w].discard(v)
                if len(adj[w]) < d:
                    q.append(w)
    return sorted(alive)


keep = kcore(len(U), E, a.degree)
P2, E2 = induced(U, E, keep)
tri = find_triangle(len(P2), E2)
t = time.time()
if a.cube:
    from hn.cubes import cube_colourable
    five = not cube_colourable(len(P2), E2, split=a.cube, procs=a.procs, log=log)
else:
    five = verify(P2, E2, triangle=tri) if tri else None
log(f"{a.degree}-core {len(P2)} points, {len(E2)} edges; chi>=5 {five}  "
    f"({time.time()-t:.0f}s)" + ("   <<<<< 5-CHROMATIC" if five else ""))
if five:
    save_points(f"out/hg{a.sets}sets.pts", P2)
    save_edges(f"out/hg{a.sets}sets.edge", len(P2), E2)
    log(f"   saved out/hg{a.sets}sets.pts")
