#!/usr/bin/env python3
"""The computational content of the divisibility law, made explicit.

To prove:  for p in the Moser lattice R with |p|^2 = a an integer,
           p in 2R  <=>  4 | a.

With q(p) := 9 |p|^2 the chain is

    4 | a   <=>   4 | 9a = q(p)   <=>   p in 2R,

the first step because gcd(4, 9) = 1.  So everything rests on

  (a) q is INTEGER-valued on R (at every point of rational norm);
  (b) q mod 2 is a well-defined function on R/2R;
  (c) q mod 2 vanishes exactly on the zero class;
  (d) p in 2R  =>  q(p) = 4 q(p/2) = 0 mod 4.

(d) is immediate from (a).  (a), (b), (c) are established here, explicitly and
reproducibly: a basis of R, the Gram matrix of q on it, and the sixteen classes.
"""
import os, sys
from fractions import Fraction
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.field import set_primes, K, Pt
set_primes((3, 5, 11))
from hn import construct as C
C.refresh_field()
from hn.construct import unit_vector_family, ball, norm
from hn.lattice import Lattice
log = lambda s: print(s, flush=True)

W = unit_vector_family(2)
R = Lattice(W)
B = R.basis
log(f"R = the Moser lattice, rank {R.rank}, generated by the 30 unit vectors.")
log("")

# ---- the Gram matrix of q = 9|.|^2 on the chosen basis ---------------------
def ip(u, v):
    """The RATIONAL PART of <u,v> = u.x v.x + u.y v.y.

    |p|^2 is not rational on R -- 92% of lattice points have a sqrt33 component,
    which is exactly the chart's side condition AB + CD != 0.  But the norm
    always lies in Q + Q sqrt33, and projecting onto the rational part is
    Q-linear, so q1(p) := ratpart(|p|^2) IS a rational quadratic form on R, and
    q1 agrees with |p|^2 precisely on the points of rational norm -- the shell
    points among them.  Index 5 of the basis is sqrt33.
    """
    z = u.x * v.x + u.y * v.y
    assert not any(z.n[i] for i in range(1, 8) if i != 5), \
        "norm has a component outside Q + Q sqrt33"
    return Fraction(z.n[0], z.d)

G = [[36 * ip(B[i], B[j]) for j in range(R.rank)] for i in range(R.rank)]
log("(a)+(b)  Gram matrix of Q(x) = 36 * ratpart(|x|^2) on a basis of R:")
for row in G:
    log("      [" + "  ".join(f"{str(x):>6}" for x in row) + "]")
diag_int = all(G[i][i].denominator == 1 for i in range(R.rank))
off_half = all((2 * G[i][j]).denominator == 1 for i in range(R.rank) for j in range(R.rank))
off_int = all(G[i][j].denominator == 1 for i in range(R.rank) for j in range(R.rank))
log(f"      diagonal integral: {diag_int}")
log(f"      off-diagonal integral: {off_int};  half-integral: {off_half}")
log("")
log("      q(sum n_i b_i) = sum_i n_i^2 G_ii + 2 sum_{i<j} n_i n_j G_ij,")
log("      so q is integer-valued whenever the diagonal is integral and the")
log("      off-diagonal is half-integral -- both hold above, giving (a).")
log("      And q(x + 2y) = q(x) + 4 B(x,y) + 4 q(y) with B half-integral, so")
log("      4B is an even integer: q mod 2 depends only on x mod 2R, giving (b).")
log("")

# ---- (c) the sixteen classes ----------------------------------------------
log("(c)  q mod 4 on each of the 2^rank classes of R/2R, at the representative")
log("     obtained from the 0/1 coordinate vector:")
log("")
log("     class     Q(rep)   Q mod 16")
zero_only = True
for m in range(1 << R.rank):
    n = [(m >> k) & 1 for k in range(R.rank)]
    qv = sum(n[i] * n[i] * G[i][i] for i in range(R.rank)) \
       + 2 * sum(n[i] * n[j] * G[i][j] for i in range(R.rank) for j in range(i + 1, R.rank))
    assert qv.denominator == 1, f"q not integral at {n}"
    qi = int(qv)
    tag = "   <-- ZERO CLASS" if m == 0 else ""
    if m and qi % 16 == 0:
        zero_only = False
        tag = "   *** 0 mod 16 off the zero class"
    log(f"     {''.join(map(str,n))}   {qi:8d}   {qi % 16:8d}{tag}")
log("")
log(f"     Q is non-zero mod 16 on every non-zero class: {zero_only}")
log("")
log("WHY THIS IS NOT YET A PROOF.")
log("  Q(x + 2y) = Q(x) + 4 B(x,y) + 4 Q(y), and B is integral above, so only")
log("  **Q mod 4** is a function of the class -- not Q mod 16.  And mod 4 the")
log("  table does not separate: classes 1000, 0010, 0101, 0111, 1111 and others")
log("  all give Q = 0 mod 4 while lying off the zero class.  Reading the mod-16")
log("  column as decisive would be reading a representative for a class.")
log("")
log("  The obstruction is structural, not a slip.  36 = 4 * 9, so scaling the")
log("  form to make it integral inserts exactly the factor 4 that the test")
log("  needs to see, and without that scaling the Gram matrix has quarter-")
log("  integer entries (-1/4, 5/4 above) and the form is not integral at all.")
log("")
log("  Two routes are now closed:")
log("    * |p|^2 itself is not rational on R -- 92% of lattice points have a")
log("      sqrt33 component, which is exactly the chart condition AB + CD != 0.")
log("    * its rational part IS a rational form, but not an integral one at any")
log("      scaling that preserves the mod-4 information.")
log("")
log("  What stands: the law is verified on 292 spindles and, point by point,")
log("  on every complete shell to squared radius 36.  The proof is open.")
