#!/usr/bin/env python3
"""The ambient lattice that actually contains every two-part construction.

Usage: sweep_ambient.py [DEPTH] [RADIUS]

Every construction is V union rho(V), and rho(V) does not lie in V's lattice:
theta_4 carries it out. So the object that contains the whole graph is the
lattice generated by the 30 unit vectors TOGETHER with their theta_4 images,
sixty vectors in all. Nobody has searched it directly; every search in the
literature and in this repository searches one of its two-part slices.

The distinction matters because the ambient lattice contains 5-chromatic
subgraphs that need not split into two isometric copies at all. A two-part
construction is a special case, and it is the only case anyone has looked at.
"""
import os, sys, time
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.field import K, Pt
from hn.construct import (unit_vector_family, ball, dedup, edges, rotate, norm,
                          ROT, ORIGIN)
from hn import verify, find_triangle

T4 = ROT["theta4"]
W30 = unit_vector_family(2)
W18 = unit_vector_family(1)
AMB = {
    "30 + theta_4(30) = 60 vectors": dedup(W30 + [rotate(v, T4) for v in W30]),
    "30 + theta_4(18) = 48 vectors": dedup(W30 + [rotate(v, T4) for v in W18]),
    "18 + theta_4(18) = 36 vectors": dedup(W18 + [rotate(v, T4) for v in W18]),
}
depth = int(sys.argv[1]) if len(sys.argv) > 1 else 2
radius = float(sys.argv[2]) if len(sys.argv) > 2 else 2.0
print(f"depth {depth}, radius {radius}", flush=True)
for name, W in AMB.items():
    t = time.time()
    V = ball(W, depth, radius)
    if len(V) > 30000:
        print(f"  {name}: {len(V)} points, too big to test here", flush=True)
        continue
    E = edges(V)
    tri = find_triangle(len(V), E)
    five = verify(V, E, triangle=tri) if tri else None
    mark = "   <<< smaller than the 2365 two-part pool" if five and len(V) < 2365 else ""
    print(f"  {name}: {len(V):6d} points, {len(E):7d} edges, chi>=5 {five}"
          f"  ({time.time()-t:.0f}s){mark}", flush=True)
