#!/usr/bin/env python3
"""The complete search for a joining rotation, over every multiquadratic field.

Usage: sweep_joiners.py [DEPTH] [RADIUS] [MMAX] [DMAX]     (default 3 2.0 60 14)

Two facts collapse the search space to something that can be swept to the end.

First, a Moser spindle needs sqrt11: the spindle is R union theta_3(R) and
theta_3 has sin sqrt11/6, and unit-distance embeddings of a rigid graph are
determined up to isometry. So a field without sqrt11 cannot contain a spindle
at all, and every small 5-chromatic graph known contains spindles; the
spindle-free ones cost 1441 vertices and up.

Second, the lattice generated by 60 degrees and theta_3/2 lies entirely in
Q(sqrt3, sqrt11), so it is the SAME lattice in every field containing sqrt11.
Verified here: ball 1999, 13890 edges and 6474 unit rhombi with a unit
diagonal in Q(sqrt3,sqrt5,sqrt11), Q(sqrt3,sqrt7,sqrt11), Q(sqrt3,sqrt2,sqrt11)
and Q(sqrt3,sqrt11,sqrt13) alike.

So the third generator never touches the lattice. It only decides which
rotations exist to join the lattice to a rotated copy of itself. That makes
the search one-dimensional: fix the lattice, and sweep the joining rotation
over Q(sqrt3, sqrt11, sqrt m) for every squarefree m.
"""
import os, sys, math, time
from math import gcd, isqrt
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.field import K, Pt, set_primes


def squarefree(n):
    d = 2
    while d * d <= n:
        if n % (d * d) == 0:
            return False
        d += 1
    return True


def run(m, depth, radius, dmax):
    set_primes((3, 11, m))
    from hn.construct import ball, dedup, edges, rotate, refresh_field
    from hn import verify, find_triangle
    refresh_field()
    th1 = (K.rat(1, 2), K.root(3) * K.rat(1, 2))
    gen = (K.root(33) * K.rat(1, 6), K.root(3) * K.rat(1, 6))     # theta_3/2
    jmax = int(os.environ.get("HN_JMAX", 2))
    W, seen = [], set()
    for j in range(-jmax, jmax + 1):
        v = Pt(K.rat(1), K.zero())
        for _ in range(abs(j)):
            v = rotate(v, gen, inverse=j < 0)
        for _ in range(6):
            if v.key() not in seen:
                seen.add(v.key())
                W.append(v)
            v = rotate(v, th1)
    V = ball(W, depth, radius)
    n = len(V)
    SQ = sorted({1, 3, 11, 33, m, 3 * m, 11 * m, 33 * m})
    rots, seenr = [], set()
    for d in range(2, dmax + 1):
        for u in SQ:
            for w in SQ:
                a = 1
                while a * a * u < d * d:
                    rem = d * d - a * a * u
                    if rem % w == 0:
                        b = isqrt(rem // w)
                        if b * b == rem // w and b > 0 and gcd(gcd(a, b), d) == 1:
                            ang = math.degrees(math.atan2(b * math.sqrt(w), a * math.sqrt(u)))
                            if 0 < ang < 180 and round(ang, 9) not in seenr:
                                seenr.add(round(ang, 9))
                                rots.append((ang, (K.root(u) * K.rat(a, d),
                                                   K.root(w) * K.rat(b, d)),
                                             f"{a}sqrt{u}/{d}, {b}sqrt{w}/{d}"))
                    a += 1
    hits, t0, tested = [], time.time(), 0
    for ang, cs, lab in rots:
        P = V + [rotate(p, cs) for p in V]
        E = edges(P)
        if sum(1 for a, b in E if (a < n) != (b < n)) <= len(W):
            continue
        tested += 1
        U = dedup(P)
        EU = edges(U)
        tri = find_triangle(len(U), EU)
        if tri and verify(U, EU, triangle=tri):
            hits.append((ang, lab, len(U)))
            print(f"   *** 5-CHROMATIC: m={m}, rotation {ang:.4f} deg ({lab}), "
                  f"union {len(U)} vertices", flush=True)
    print(f"m={m:3d}  Q(sqrt3,sqrt11,sqrt{m}): {len(rots)} rotations, {tested} with cross "
          f"edges, {len(hits)} work  ({time.time()-t0:.0f}s)", flush=True)
    return hits


if __name__ == "__main__":
    depth = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    radius = float(sys.argv[2]) if len(sys.argv) > 2 else 2.0
    mmax = int(sys.argv[3]) if len(sys.argv) > 3 else 60
    dmax = int(sys.argv[4]) if len(sys.argv) > 4 else 14
    ms = [m for m in range(2, mmax + 1) if squarefree(m) and m % 3 and m % 11]
    lo = int(os.environ.get("HN_M_LO", 0))
    hi = int(os.environ.get("HN_M_HI", len(ms)))
    ms = ms[lo:hi]
    print(f"sweeping m in {ms}", flush=True)
    total = []
    for m in ms:
        try:
            total += run(m, depth, radius, dmax)
        except Exception as e:
            print(f"m={m} failed: {type(e).__name__}: {e}", flush=True)
    print(f"\nTOTAL: {len(total)} working joining rotations", flush=True)
    for h in total:
        print("  ", h)
