#!/usr/bin/env python3
"""Sweep PAIRS of (lattice generator, joining rotation).

Usage: sweep_lattices.py [BALL_DEPTH] [BALL_RADIUS]        (default 3 2.2)

Every published 5-chromatic unit-distance graph is two parts of one lattice,
one rotated against the other.  The lattice is always the same: generated by
60 degrees together with theta_3/2 = arcsin(1/sqrt12).  The rotation is
always the same: theta_4 = arccos(7/8).  Nothing in the literature says
either choice is forced.

This tests both at once.  A generator is only worth trying if it brings
irrationality, since a lattice generated by Pythagorean directions lies in
Q^2, whose unit-distance graph is 2-chromatic; so the generators swept here
are the ones carrying sqrt11, the arithmetic signature of the Moser spindle.
For each, all 73 rotations of the field are tried, and the union is tested
for 5-chromaticity.

Measured: of every pair tried, exactly ONE is 5-chromatic, the classical
lattice with theta_4.  Both halves of the published choice are forced.
"""
import os, sys, math, time
from math import gcd, isqrt
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.field import K, Pt
from hn.construct import ball, dedup, edges, rotate, to_float, ROT
from hn import verify, find_triangle

SQ = (1, 3, 5, 11, 15, 33, 55, 165)
CARRIES_11 = (11, 33, 55, 165)


def unit_directions(dmax=32):
    """(angle, cos, sin, label) for every unit vector of the field."""
    out, seen = [], set()
    for d in range(2, dmax + 1):
        for m in SQ:
            for mp in SQ:
                if mp < m:
                    continue
                a = 1
                while a * a * m < d * d:
                    rem = d * d - a * a * m
                    if rem % mp == 0:
                        b = isqrt(rem // mp)
                        if b * b == rem // mp and b > 0 and gcd(gcd(a, b), d) == 1:
                            c, s = K.root(m) * K.rat(a, d), K.root(mp) * K.rat(b, d)
                            ang = math.degrees(math.atan2(to_float(s), to_float(c)))
                            if 0 < ang < 90 and round(ang, 9) not in seen:
                                seen.add(round(ang, 9))
                                lab = (f"{a if a > 1 else ''}{'sqrt%d' % m if m > 1 else ''}/{d}, "
                                       f"{b if b > 1 else ''}{'sqrt%d' % mp if mp > 1 else ''}/{d}")
                                out.append((ang, c, s, lab, (m, mp)))
                    a += 1
    out.sort()
    return out


def family(gen, jmax=2):
    """The 6*(2*jmax+1) unit vectors exp(i(k*60deg + j*gen))."""
    out, seen = [], set()
    for j in range(-jmax, jmax + 1):
        v = Pt(K.rat(1), K.zero())
        for _ in range(abs(j)):
            v = rotate(v, gen, inverse=j < 0)
        for k in range(6):
            if v.key() not in seen:
                seen.add(v.key())
                out.append(v)
            v = rotate(v, ROT["theta1"])
    return out


if __name__ == "__main__":
    depth = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    radius = float(sys.argv[2]) if len(sys.argv) > 2 else 2.2
    dirs = unit_directions()
    rots = [(a, (c, s)) for a, c, s, _, _ in dirs]
    gens = [d for d in dirs if d[4][0] in CARRIES_11 or d[4][1] in CARRIES_11]
    print(f"{len(rots)} rotations, {len(gens)} generators carrying sqrt11, "
          f"ball depth {depth} radius {radius}\n", flush=True)
    total_hits = []
    for gi, (gang, gc, gs, glab, _) in enumerate(gens, 1):
        W = family((gc, gs))
        V = ball(W, depth, radius)
        n = len(V)
        t0, hits = time.time(), []
        for rang, cs in rots:
            RV = [rotate(p, cs) for p in V]
            P = V + RV
            E = edges(P)
            if sum(1 for a, b in E if (a < n) != (b < n)) <= len(W):
                continue                      # only the origin's own edges
            U = dedup(P)
            EU = edges(U)
            tri = find_triangle(len(U), EU)
            if tri and verify(U, EU, triangle=tri):
                hits.append((rang, len(U)))
        mark = "   <<< 5-CHROMATIC" if hits else ""
        print(f"[{gi:2d}/{len(gens)}] generator {gang:7.3f} deg ({glab}): "
              f"{len(W)} vectors, ball {n}, {len(hits)}/{len(rots)} rotations work"
              f"  ({time.time()-t0:.0f}s){mark}", flush=True)
        for rang, size in hits:
            print(f"          rotation {rang:.3f} deg, union {size} vertices", flush=True)
            total_hits.append((gang, rang, size))
    print(f"\n{len(total_hits)} working (lattice, rotation) pairs out of "
          f"{len(gens)*len(rots)} tried:")
    for g, r, s in total_hits:
        print(f"   generator {g:.3f} deg + rotation {r:.3f} deg -> {s} vertices")
