#!/usr/bin/env python3
"""Deep sweep over the generators that the classical construction actually uses.

Usage: sweep_halfspindle.py DEPTH RADIUS        (HN_FIELD=p,q,r selects the field)

The classical lattice is generated by 60 degrees and theta_3/2, which is HALF
a spindle angle, and that is not an accident: two steps of theta_3/2 give
theta_3, so the Moser spindle is realizable inside the lattice itself, which
is what supplies the sqrt3-triangle structure de Grey's argument runs on.

So the principled generators in any field are the half-spindles theta_i/2,
with cos = sqrt(4i-1)/(2 sqrt i) and sin = 1/(2 sqrt i), for those i where both
roots live in the field. This sweeps exactly those, at a ball depth the broad
sweep cannot afford, against every rotation of the field.
"""
import os, sys, math, time
from math import gcd, isqrt
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from hn.field import K, Pt, set_primes
from sweep_fields import squarefree_divisors, spindles, unit_directions


def half_spindles(primes):
    """(i, cos, sin) for each theta_i/2 that lives in this field."""
    out = []
    for i, _, _ in spindles(primes, 80):
        m = 4 * i - 1
        for s in squarefree_divisors(primes):
            if (i * m) % s:
                continue
            r = isqrt((i * m) // s)
            if r * r != (i * m) // s:
                continue
            for s2 in squarefree_divisors(primes):
                if i % s2:
                    continue
                r2 = isqrt(i // s2)
                if r2 * r2 != i // s2:
                    continue
                # cos = sqrt(i(4i-1)) / (2i),  sin = sqrt(i) / (2i)
                c = K.root(s) * K.rat(r, 2 * i)
                sn = K.root(s2) * K.rat(r2, 2 * i)
                if (c * c + sn * sn).is_one():
                    out.append((i, c, sn))
                break
            break
    return out


if __name__ == "__main__":
    depth = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    radius = float(sys.argv[2]) if len(sys.argv) > 2 else 2.0
    pr = tuple(int(x) for x in os.environ.get("HN_FIELD", "3,5,11").split(","))
    set_primes(pr)
    from hn.construct import ball, dedup, edges, rotate, refresh_field
    from hn import verify, find_triangle
    refresh_field()
    th1 = (K.rat(1, 2), K.root(3) * K.rat(1, 2))
    hs = half_spindles(pr)
    dirs = unit_directions(pr, 14)
    sp = spindles(pr)
    rots = [(a, (c, s)) for a, c, s, _ in dirs] + \
           [(math.degrees(math.acos((2 * i - 1) / (2 * i))), (c, s)) for i, c, s in sp]
    print(f"field Q(sqrt{pr[0]},sqrt{pr[1]},sqrt{pr[2]}): half-spindles for i = "
          f"{[i for i, _, _ in hs]}, {len(rots)} rotations, ball depth {depth} r {radius}",
          flush=True)
    for i, gc, gs in hs:
        W, seen = [], set()
        for j in (-2, -1, 0, 1, 2):
            v = Pt(K.rat(1), K.zero())
            for _ in range(abs(j)):
                v = rotate(v, (gc, gs), inverse=j < 0)
            for _ in range(6):
                if v.key() not in seen:
                    seen.add(v.key())
                    W.append(v)
                v = rotate(v, th1)
        V = ball(W, depth, radius)
        n = len(V)
        t0, hits = time.time(), 0
        for rang, cs in rots:
            P = V + [rotate(p, cs) for p in V]
            E = edges(P)
            if sum(1 for a, b in E if (a < n) != (b < n)) <= len(W):
                continue
            U = dedup(P)
            EU = edges(U)
            tri = find_triangle(len(U), EU)
            if tri and verify(U, EU, triangle=tri):
                hits += 1
                print(f"   *** 5-CHROMATIC: generator theta_{i}/2 + rotation "
                      f"{rang:.3f} deg, union {len(U)} vertices", flush=True)
        print(f"  theta_{i}/2: {len(W)} vectors, ball {n}, {hits} rotations work "
              f"({time.time()-t0:.0f}s)", flush=True)
