#!/usr/bin/env python3
"""Sweep other coordinate FIELDS, not just other lattices inside one field.

Usage: sweep_fields.py [DEPTH] [RADIUS] [MAXDEN]        (default 3 2.2 16)

Every 5-chromatic unit-distance graph in the literature lives in
Q(sqrt3, sqrt5, sqrt11). That is not a choice anybody defends: it is the field
de Grey's 2018 graph happened to need, and every later construction inherited
it. Nothing about the problem prefers it.

The representation in hn/field.py is generic in the three squarefree
generators, so the field is a parameter. What changes with it is which spindle
rotations exist at all. A rotation theta_i, with cos = (2i-1)/(2i) and
sin = sqrt(4i-1)/(2i), turns two points at distance sqrt(i) from a centre into
a unit edge, and it exists only when 4i-1 is a square times a squarefree
divisor of the field's generators. In the classical field that admits
theta_1, theta_3, theta_4, theta_7 and a few more; theta_2, which needs
sqrt7, has never been available to anyone working on this problem.

For each field this sweeps lattices generated by 60 degrees together with one
other unit direction, against every rotation of that field, and reports which
pairs give a 5-chromatic union.
"""
import os, sys, math, time
from math import gcd, isqrt
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import hn.field as F
from hn.field import K, Pt, set_primes


def squarefree_divisors(primes):
    out = [1]
    for p in primes:
        out += [d * p for d in out]
    return sorted(out)


def unit_directions(primes, dmax):
    """(angle, cos, sin, label) for the unit vectors of this field."""
    SQ = squarefree_divisors(primes)
    r3 = math.sqrt
    out, seen = [], set()
    for d in range(2, dmax + 1):
        for m in SQ:
            for mp in SQ:
                a = 1
                while a * a * m < d * d:
                    rem = d * d - a * a * m
                    if rem % mp == 0:
                        b = isqrt(rem // mp)
                        if b * b == rem // mp and b > 0 and gcd(gcd(a, b), d) == 1:
                            ang = math.degrees(math.atan2(b * r3(mp), a * r3(m)))
                            key = round(ang, 9)
                            if 0 < ang < 90 and key not in seen:
                                seen.add(key)
                                out.append((ang, K.root(m) * K.rat(a, d),
                                            K.root(mp) * K.rat(b, d),
                                            f"{a}sqrt{m}/{d}, {b}sqrt{mp}/{d}"))
                    a += 1
    out.sort()
    return out


def spindles(primes, imax=60):
    """The rotations theta_i this field admits, with the radius they spindle."""
    SQ = squarefree_divisors(primes)
    out = []
    for i in range(1, imax + 1):
        m = 4 * i - 1
        for s in SQ:
            if m % s == 0 and isqrt(m // s) ** 2 == m // s:
                r = isqrt(m // s)
                out.append((i, K.rat(2 * i - 1, 2 * i), K.root(s) * K.rat(r, 2 * i)))
                break
    return out


def run_field(primes, depth, radius, dmax):
    set_primes(primes)
    from hn.construct import ball, dedup, edges, rotate, refresh_field
    refresh_field()      # the float basis AND the rotation table depend on the field
    from hn import verify, find_triangle
    theta1 = (K.rat(1, 2), K.root(3) * K.rat(1, 2))
    dirs = unit_directions(primes, dmax)
    sp = spindles(primes)
    rots = [(a, (c, s)) for a, c, s, _ in dirs] + \
           [(math.degrees(math.acos((2 * i - 1) / (2 * i))), (c, s)) for i, c, s in sp]
    print(f"\n########  field Q(sqrt{primes[0]}, sqrt{primes[1]}, sqrt{primes[2]})", flush=True)
    print(f"  spindle rotations theta_i available: {[i for i, _, _ in sp]}", flush=True)
    print(f"  {len(dirs)} unit directions, {len(rots)} rotations to try", flush=True)
    hits = []
    for gi, (gang, gc, gs, glab) in enumerate(dirs, 1):
        W, seen = [], set()
        for j in (-2, -1, 0, 1, 2):
            v = Pt(K.rat(1), K.zero())
            for _ in range(abs(j)):
                v = rotate(v, (gc, gs), inverse=j < 0)
            for _ in range(6):
                if v.key() not in seen:
                    seen.add(v.key())
                    W.append(v)
                v = rotate(v, theta1)
        V = ball(W, depth, radius)
        n = len(V)
        if n < 300:
            continue
        t0, local = time.time(), []
        for rang, cs in rots:
            RV = [rotate(p, cs) for p in V]
            P = V + RV
            E = edges(P)
            if sum(1 for a, b in E if (a < n) != (b < n)) <= len(W):
                continue
            U = dedup(P)
            EU = edges(U)
            tri = find_triangle(len(U), EU)
            if tri and verify(U, EU, triangle=tri):
                local.append((rang, len(U)))
                print(f"     *** 5-CHROMATIC: generator {gang:.3f} ({glab}) "
                      f"+ rotation {rang:.3f}, union {len(U)} vertices", flush=True)
        print(f"  [{gi:2d}/{len(dirs)}] generator {gang:7.3f} ({glab}): {len(W)} vectors, "
              f"ball {n}, {len(local)}/{len(rots)} work  ({time.time()-t0:.0f}s)", flush=True)
        hits += [(gang, r, s) for r, s in local]
    print(f"  field total: {len(hits)} working pairs", flush=True)
    return hits


if __name__ == "__main__":
    depth = int(sys.argv[1]) if len(sys.argv) > 1 else 3
    radius = float(sys.argv[2]) if len(sys.argv) > 2 else 2.2
    dmax = int(sys.argv[3]) if len(sys.argv) > 3 else 16
    FIELDS = [(3, 5, 11), (3, 5, 7), (3, 7, 11), (3, 2, 7), (3, 2, 5),
              (3, 7, 13), (3, 5, 13), (3, 11, 13), (3, 2, 11), (3, 5, 19)]
    only = os.environ.get("HN_FIELD")
    if only:
        FIELDS = [tuple(int(x) for x in only.split(","))]
    for pr in FIELDS:
        try:
            run_field(pr, depth, radius, dmax)
        except Exception as e:
            print(f"  field {pr} failed: {type(e).__name__}: {e}", flush=True)
