#!/usr/bin/env python3
"""de Grey's 2026 conjecture at d = 2, n = 3, over the fields where it can live.

Usage: trianglefree.py [--nmax 30] [--box 2]

> **Conjecture (de Grey, Polymath16 thread 18, 17 Jan 2026).**  For all `d >= 2`
> and `3 <= n <= d+2` there is a `(d+n-1)`-chromatic unit-distance graph in `R^d`
> containing no `n`-simplex.

The `d = 2, n = 3` case asks for a **triangle-free 5-chromatic unit-distance
graph in the plane**.  All 69 comments of that thread are about the conjecture;
the 509-vertex record is not mentioned once.

## Where a triangle cannot be

A unit equilateral triangle `p, p+u, p+v` has `|u| = |v| = |u-v| = 1`, which
forces `v/u` to be a primitive 6th root of unity.  So a subgroup of `Q(zeta_n)`
contains a unit triangle only if `zeta_6` lies in `Q(zeta_n)`, and

    zeta_6 in Q(zeta_n)   <=>   3 | n

(for odd `n`, `Q(zeta_n) = Q(zeta_2n)`, so the condition is `6 | 2n`).  Hence:

> **For every `n` with `3` not dividing `n`, every subgroup of `Q(zeta_n)` is
> triangle-free as a unit-distance graph, and so is every subgraph of it.**

That is why Haugland's construction does not settle the conjecture: it lives on
`zeta_42`, and `3 | 42`.

## What is then left to decide

Whether any such group can host a 5-chromatic unit-distance graph at all.  The
ball-free filter answers that with a **proof** whenever it finds a homomorphism
`phi : Lambda -> G`, `|G| = 4`, killing no unit vector: then the whole infinite
group is 4-colourable, at every radius, so no subgraph of it is 5-chromatic.

## Which groups to try

By Kronecker, an algebraic *integer* with all conjugates of modulus 1 is a root
of unity, so `Z[zeta_n]` has only the `2n` (or `n`) roots of unity as unit
vectors -- a thin Cayley graph.  The rich ones have denominators, and Hilbert 90
gives them all: every modulus-1 element of `Q(zeta_n)` is `w / conj(w)`.  So the
sweep runs over the groups generated by the `w / conj(w)` for `w` in a small box.
"""
import os, sys, time, argparse, itertools
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

ap = argparse.ArgumentParser()
ap.add_argument("--nmax", type=int, default=30)
ap.add_argument("--box", type=int, default=2, help="coefficient range for w")
ap.add_argument("--only", type=int, default=None)
ap.add_argument("--limit", type=int, default=8, help="rotations to try per n")
a = ap.parse_args()
log = lambda s: print(s, flush=True)

import hn.cyclo as CY
from hn.cyclolat import CycLattice
from hn.algcolour import klein_colourings, z4_colourings

# Haugland's shape, in a field where triangles cannot exist: the roots of unity
# together with ONE extra unit vector rho and its rotates -- "two sets of 42
# vectors" in his case.  Generating instead by every w/conj(w) in a box makes a
# group so fine that its unit-vector ellipsoid is not enumerable, and a group
# that fine is not what a construction looks like anyway.
log(f"{'n':>4} {'deg':>4} {'rho':>18} {'rank':>5} {'units':>6}  verdict")
survivors = []
for n in ([a.only] if a.only else range(4, a.nmax + 1)):
    if n % 3 == 0 or n % 4 == 2:
        continue
    CY.set_conductor(n)
    deg = CY.DEG
    if deg > 16:
        log(f"{n:>4} {deg:>4}  skipped: degree too large")
        continue
    m = n if n % 2 == 0 else 2 * n              # the roots of unity present
    roots = [CY.Cyc.zeta(k) if k < deg else None for k in range(0)]
    # zeta_n^k for k = 0..n-1, plus -1 when n is odd, is the full root group
    base = []
    seen = set()
    for k in range(n):
        z = CY.Cyc.zeta(k)
        for sgn in ((1,) if n % 2 == 0 else (1, -1)):
            w = z if sgn == 1 else CY.Cyc.zero() - z
            if w.key() not in seen:
                seen.add(w.key()); base.append(w)
    rhos = {}
    rng = range(-a.box, a.box + 1)
    for coef in itertools.product(rng, repeat=min(deg, 4)):
        if all(c == 0 for c in coef):
            continue
        w = CY.Cyc(tuple(list(coef) + [0] * (deg - len(coef))), 1)
        cw = w.conj()
        if cw.is_zero():
            continue
        try:
            z = w / cw
        except Exception:
            continue
        if not (z * z.conj()).is_one():
            continue
        if z.key() in seen:                      # already a root of unity
            continue
        rhos[z.key()] = z
    log(f"{n:>4} {deg:>4}   {len(base)} roots, {len(rhos)} extra rotations to try")
    for key, rho in sorted(rhos.items())[:a.limit]:
        t = time.time()
        gens = base + [rho * b for b in base]
        L = CycLattice(gens)
        if L.rank > 12:
            continue
        try:
            uv = L.unit_vectors()
        except Exception as e:
            log(f"       rho {str(key)[:14]:14} rank {L.rank}: enumeration failed")
            continue
        coords = [c for c, _ in uv]
        kl = klein_colourings(coords, L.rank)
        z4 = z4_colourings(coords, L.rank)
        dead = bool(kl or z4)
        if not dead:
            survivors.append((n, str(key)[:20], L.rank, len(uv)))
        log(f"       rho {str(key)[:14]:14} rank {L.rank:>2} units {len(uv):>4}  "
            + ("4-colourable, proved" if dead else "**SURVIVES**")
            + f"  ({time.time()-t:.0f}s)")
log("")
if survivors:
    log(f"SURVIVORS -- triangle-free groups no periodic 4-colouring kills:")
    for s_ in survivors:
        log(f"   {s_}")
    log("Each is a candidate home for a triangle-free 5-chromatic unit-distance graph.")
else:
    log("No survivor: every triangle-free group tried is provably 4-colourable,")
    log("which is evidence against the conjecture at d = 2, n = 3 in this setting.")
